#!/usr/bin/env python3
"""Prebuild step for the NetSurf PAPP (apps/netsurf/papp.json).

NetSurf and its libraries generate some sources with host tools before they
compile. This does the same with the build machine's tools, inside the source
checkout that tools/build_papp.py prepared:

- libcss: the property parsers (css_property_parser_gen, from properties.gen)
- libhubbub: the entity table (make-entities.pl) and the element-type hash
  (gperf; written to .papp-gen/hubbub so the "*.c" group does not pick it up)
- libparserutils: the charset alias table (make-aliases.pl)
- libsvgtiny: the colour name hash (gperf; .papp-gen/svgtiny, which
  svgtiny_parse.c includes)
- NetSurf framebuffer frontend: the toolkit images (the PNG icons, pointers
  and throbber decoded here instead of with libpng, in convert_image's output
  format) and testament.h
- the fonts: subsets of the DejaVu fonts (fontTools' subsetter, run from its
  pinned checkout), compiled in (papp_fonts.c)
- the resources NetSurf serves from resource: URLs and its Messages file,
  compiled in (papp_resources.c), so the app runs with nothing on the card;
  licence.html also gets the licences of the fonts and the libraries 0.3
  added
- libdom's hubbub and XML binding headers as <dom/bindings/...>
- libpng's pnglibconf.h (its prebuilt default), libjpeg-turbo's
  jconfig.h/jconfigint.h/jversion.h (what its CMake step would write) and
  expat's expat_config.h, with the public headers of those, libwebp's decoder
  and expat in .papp-gen/include

With --units it then prints the compiler's warnings for the port's own
files and the patched NetSurf files (the build itself only shows errors).

Everything is reproducible: no timestamps, host names or paths end up in the
output except what SOURCE_DATE_EPOCH gives.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import struct
import subprocess
import sys
import time
import zlib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
PORT = REPO / "ports" / "netsurf"


def log(msg: str) -> None:
    print(f"  [gen] {msg}", flush=True)


def run(cmd: list[str], **kwargs) -> None:
    subprocess.run([str(c) for c in cmd], check=True, **kwargs)


def need(tool: str, package: str) -> str:
    """Path of a host tool; installs its Debian package if it is missing (CI container)."""
    found = shutil.which(tool)
    if found:
        return found
    if shutil.which("apt-get") and hasattr(os, "geteuid") and os.geteuid() == 0:
        log(f"{tool} missing, installing {package}")
        subprocess.run(["apt-get", "update", "-qq"], check=False, stdout=subprocess.DEVNULL)
        subprocess.run(["apt-get", "install", "-y", "-qq", package], check=False, stdout=subprocess.DEVNULL)
        found = shutil.which(tool)
    if not found:
        raise SystemExit(f"gen_netsurf: '{tool}' is needed (package {package})")
    return found


# Perl randomises hash order on every run, and make-entities.pl builds its
# search tree in `keys %entities` order: without a fixed seed each build had a
# different entities.inc, so a rebuild of the same commit made a new binary.
PERL_ENV = {**os.environ, "PERL_HASH_SEED": "0", "PERL_PERTURB_KEYS": "0"}


def host_cc() -> str:
    return shutil.which("cc") or shutil.which("gcc") or need("gcc", "gcc")


# ── libcss ──────────────────────────────────────────────────────────────────

def gen_libcss(src: Path, gen: Path) -> None:
    props = src / "libs/libcss/src/parse/properties"
    tool = gen / "tools" / "css_property_parser_gen"
    tool.parent.mkdir(parents=True, exist_ok=True)
    run([host_cc(), "-O1", "-o", tool, props / "css_property_parser_gen.c"])
    count = 0
    for line in (props / "properties.gen").read_text().splitlines():
        m = re.match(r"^([^#][^:]+):", line)
        if not m:
            continue
        run([tool, "-o", props / f"autogenerated_{m.group(1)}.c", line.strip()], stdout=subprocess.DEVNULL)
        count += 1
    log(f"libcss: {count} property parsers")


# ── libhubbub / libparserutils ──────────────────────────────────────────────

def gen_hubbub(src: Path, gen: Path) -> None:
    lib = src / "libs/libhubbub"
    run([need("perl", "perl"), "build/make-entities.pl"], cwd=lib, stdout=subprocess.DEVNULL, env=PERL_ENV)
    out = gen / "hubbub" / "treebuilder" / "autogenerated-element-type.c"
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_suffix(".tmp")
    run([need("gperf", "gperf"), f"--output-file={tmp}", lib / "src/treebuilder/element-type.gperf"])
    text = tmp.read_text()
    tmp.unlink()
    # As the upstream Makefile's sed: the table is file-local.
    text = re.sub(r"^(const struct element_type_map)", r"static \1", text, flags=re.M)
    # gperf records the input path in #line directives; keep it out of the build.
    text = text.replace(str(lib) + "/", "")
    out.write_text(text)
    log("libhubbub: entities.inc, autogenerated-element-type.c")


def gen_parserutils(src: Path) -> None:
    run([need("perl", "perl"), "build/make-aliases.pl"], cwd=src / "libs/libparserutils", stdout=subprocess.DEVNULL,
        env=PERL_ENV)
    log("libparserutils: aliases.inc")


def gen_svgtiny(src: Path, gen: Path) -> None:
    """libsvgtiny's colour names (its Makefile's gperf and sed steps)."""
    lib = src / "libs/libsvgtiny"
    out = gen / "svgtiny" / "autogenerated_colors.c"
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_suffix(".tmp")
    run([need("gperf", "gperf"), f"--output-file={tmp}", lib / "src/colors.gperf"])
    text = tmp.read_text()
    tmp.unlink()
    text = re.sub(r"^(const struct svgtiny_named_color)", r"static \1", text, flags=re.M)
    text = text.replace(str(lib) + "/", "")  # #line directives name the input
    out.write_text(text)
    log("libsvgtiny: autogenerated_colors.c")


def gen_image_libs(src: Path, gen: Path) -> None:
    """The configuration headers libpng and libjpeg-turbo make with their
    configure/CMake steps, and their public headers in .papp-gen/include."""
    inc = gen / "include"
    inc.mkdir(parents=True, exist_ok=True)
    png = src / "libs/libpng"
    shutil.copyfile(png / "scripts/pnglibconf.h.prebuilt", inc / "pnglibconf.h")
    for name in ("png.h", "pngconf.h"):
        shutil.copyfile(png / name, inc / name)

    jpeg = src / "libs/libjpeg-turbo"
    cmake = (jpeg / "CMakeLists.txt").read_text()
    version = re.search(r"set\(VERSION ([0-9.]+)\)", cmake).group(1)
    major, minor, patch = (version.split(".") + ["0", "0"])[:3]
    # 8-bit samples, arithmetic decoding, no SIMD (none for RISC-V), the
    # libjpeg v6b API (JPEG_LIB_VERSION 62), as CMake's defaults.
    (inc / "jconfig.h").write_text(f"""/* Generated by ports/netsurf/gen_netsurf.py (libjpeg-turbo's jconfig.h.in). */
#define JPEG_LIB_VERSION  62
#define LIBJPEG_TURBO_VERSION  {version}
#define LIBJPEG_TURBO_VERSION_NUMBER  {int(major) * 1000000 + int(minor) * 1000 + int(patch)}
#define D_ARITH_CODING_SUPPORTED 1
#define MEM_SRCDST_SUPPORTED 1
#define BITS_IN_JSAMPLE  8
""")
    (inc / "jconfigint.h").write_text(f"""/* Generated by ports/netsurf/gen_netsurf.py (libjpeg-turbo's jconfigint.h.in). */
#define BUILD  "papp"
#undef inline
#define INLINE  __inline__ __attribute__((always_inline))
#define THREAD_LOCAL
#define PACKAGE_NAME  "libjpeg-turbo"
#define VERSION  "{version}"
#define SIZEOF_SIZE_T  4
#define HAVE_BUILTIN_CTZL
#if defined(__has_attribute)
#if __has_attribute(fallthrough)
#define FALLTHROUGH  __attribute__((fallthrough));
#else
#define FALLTHROUGH
#endif
#else
#define FALLTHROUGH
#endif
""")
    text = (jpeg / "jversion.h.in").read_text().replace("@COPYRIGHT_YEAR@", "1991-2023")
    (inc / "jversion.h").write_text(text)
    for name in ("jpeglib.h", "jmorecfg.h", "jerror.h"):
        shutil.copyfile(jpeg / name, inc / name)

    # libwebp's decoder: its public headers only (its own sources include
    # "src/..." from the checkout, which is not on the global include path:
    # libwebp's src/utils/ would shadow NetSurf's utils/).
    (inc / "webp").mkdir(exist_ok=True)
    for name in ("decode.h", "types.h"):
        shutil.copyfile(src / "libs/libwebp/src/webp" / name, inc / "webp" / name)
    log(f"image libraries: pnglibconf.h, libjpeg-turbo {version} configuration, libwebp headers")


def gen_expat(src: Path, gen: Path) -> None:
    """expat_config.h (what expat's CMake step writes for this target) and
    expat's public headers. No entropy source: the hash salt of expat's
    tables is not secret here (XML_POOR_ENTROPY)."""
    lib = src / "libs/expat/expat/lib"
    inc = gen / "include"
    inc.mkdir(parents=True, exist_ok=True)
    for name in ("expat.h", "expat_external.h"):
        shutil.copyfile(lib / name, inc / name)
    cfg = gen / "expat"
    cfg.mkdir(parents=True, exist_ok=True)
    (cfg / "expat_config.h").write_text("""/* Generated by ports/netsurf/gen_netsurf.py (expat's expat_config.h.cmake). */
#ifndef EXPAT_CONFIG_H
#define EXPAT_CONFIG_H 1
#define BYTEORDER 1234
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define PACKAGE "expat"
#define STDC_HEADERS 1
#define XML_CONTEXT_BYTES 1024
#define XML_DTD 1
#define XML_GE 1
#define XML_NS 1
#define XML_POOR_ENTROPY 1
#endif
""")
    log("expat: expat_config.h")


def gen_dom_headers(src: Path, gen: Path) -> None:
    for binding, names in (("hubbub", ("parser.h", "errors.h")), ("xml", ("xmlparser.h", "xmlerror.h"))):
        out = gen / "include" / "dom" / "bindings" / binding
        out.mkdir(parents=True, exist_ok=True)
        for name in names:
            shutil.copyfile(src / "libs/libdom/bindings" / binding / name, out / name)


# ── Fonts ───────────────────────────────────────────────────────────────────
# The DejaVu fonts (2.35, as matplotlib ships them) for FreeType
# (ports/netsurf/papp_font.c): sans-serif, serif and monospace, regular and
# bold. Italics are these slanted, unless the card has the real ones (see
# papp_font.c). Each is cut down to the characters below and has its
# hinting instructions removed (FreeType's autofitter hints instead), which
# takes the six from 2.9 MB to about 0.5 MB. The full fonts in
# /sd/roms/netsurf/fonts/ replace them.

FONT_DIR = "fonts/matplotlib/lib/matplotlib/mpl-data/fonts/ttf"
FONTS = ("DejaVuSans.ttf", "DejaVuSans-Bold.ttf", "DejaVuSerif.ttf", "DejaVuSerif-Bold.ttf",
         "DejaVuSansMono.ttf", "DejaVuSansMono-Bold.ttf")
FONT_CHARS = ",".join((
    "20-7E", "A0-24F",           # Latin-1, Latin Extended-A and -B
    "2C6-2C7", "2D8-2DD",        # spacing accents
    "370-3FF",                   # Greek
    "400-45F", "490-491",        # Cyrillic (Russian, Ukrainian, Belarusian, Serbian, Bulgarian, ...)
    "2000-206F",                 # punctuation: dashes, quotes, bullets, spaces
    "20A0-20BF",                 # currency
    "2103", "2116", "2122", "2126", "212E",       # degree Celsius, numero, trade mark, ohm, estimated
    "2190-2199", "21B5", "21B9", "21D0-21D5", "21E7",  # arrows (and the on-screen keyboard's)
    "2202", "2206", "220F", "2211-2212", "2215", "2219-221A", "221E", "2227-222B",
    "2248", "2260-2261", "2264-2265",                  # common maths
    "2302", "2318", "232B", "23CE",                    # keys (the on-screen keyboard's)
    "2500-257F", "25A0-25FF",                          # box drawing, geometric shapes
    "2605-2606", "2610-2612", "2630", "263A-263C", "2660-2667", "266A-266B",
    "2713-2718", "2764", "27A1",                       # stars, ballot boxes, suits, ticks, ...
    "FFFD",                                            # replacement character
))


def gen_fonts(src: Path, gen: Path) -> None:
    fonttools = src / "libs/fonttools/Lib"
    env = {**os.environ, "PYTHONPATH": str(fonttools), "PYTHONHASHSEED": "0", "PYTHONDONTWRITEBYTECODE": "1"}
    out = gen / "fonts"
    out.mkdir(parents=True, exist_ok=True)
    lines = ["/* Generated by ports/netsurf/gen_netsurf.py: DejaVu fonts, cut down (see FONTS there). */",
             "#include <stddef.h>", "#include <stdint.h>", '#include "papp_fonts.h"', ""]
    table = []
    total_in = total_out = 0
    for i, name in enumerate(FONTS):
        font = src / FONT_DIR / name
        subset = out / name
        run([sys.executable, "-m", "fontTools.subset", font, f"--output-file={subset}",
             f"--unicodes={FONT_CHARS}", "--no-hinting", "--layout-features=", "--notdef-outline",
             "--drop-tables+=GSUB,GPOS,GDEF,kern,FFTM", "--name-IDs=0,1,2,3,4,5,6,13,14", "--no-recalc-timestamp"],
            env=env, stdout=subprocess.DEVNULL)
        data = subset.read_bytes()
        total_in += font.stat().st_size
        total_out += len(data)
        lines += c_bytes(f"font_{i}", data) + [""]
        table.append(f'\t{{"{name}", font_{i}, {len(data)}}},')
    shutil.rmtree(out)
    lines += ["const struct papp_font papp_fonts[] = {", *table, "\t{NULL, NULL, 0}", "};", ""]
    (gen / "papp_fonts.c").write_text("\n".join(lines))
    log(f"fonts: {len(FONTS)} DejaVu fonts, {total_in} bytes cut down to {total_out}")


# ── Framebuffer toolkit images ──────────────────────────────────────────────
# frontends/framebuffer/Makefile's FB_IMAGE_* list, converted like
# tools/convert_image.c does with libpng.

FB_IMAGES = {
    "left_arrow": "icons/back.png",
    "right_arrow": "icons/forward.png",
    "reload": "icons/reload.png",
    "stop_image": "icons/stop.png",
    "history_image": "icons/history.png",
    "left_arrow_g": "icons/back_g.png",
    "right_arrow_g": "icons/forward_g.png",
    "reload_g": "icons/reload_g.png",
    "stop_image_g": "icons/stop_g.png",
    "history_image_g": "icons/history_g.png",
    "scrolll": "icons/scrolll.png",
    "scrollr": "icons/scrollr.png",
    "scrollu": "icons/scrollu.png",
    "scrolld": "icons/scrolld.png",
    "osk_image": "icons/osk.png",
    "pointer_image": "pointers/default.png",
    "hand_image": "pointers/point.png",
    "caret_image": "pointers/caret.png",
    "menu_image": "pointers/menu.png",
    "progress_image": "pointers/progress.png",
    "move_image": "pointers/move.png",
    **{f"throbber{i}": f"throbber/throbber{i}.png" for i in range(9)},
}


def png_rgba(data: bytes) -> tuple[int, int, bytes]:
    """Decode a PNG to 8-bit RGBA (what convert_image asks libpng for)."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    pos, idat, plte, trns = 8, b"", b"", None
    width = height = depth = ctype = interlace = 0
    while pos < len(data):
        length, kind = struct.unpack(">I4s", data[pos:pos + 8])
        body = data[pos + 8:pos + 8 + length]
        pos += 12 + length
        if kind == b"IHDR":
            width, height, depth, ctype, _, _, interlace = struct.unpack(">IIBBBBB", body)
        elif kind == b"PLTE":
            plte = body
        elif kind == b"tRNS":
            trns = body
        elif kind == b"IDAT":
            idat += body
        elif kind == b"IEND":
            break
    if interlace:
        raise ValueError("interlaced PNGs are not supported")
    channels = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ctype]
    bits = channels * depth
    stride = (width * bits + 7) // 8
    bpp = max(1, bits // 8)
    raw = zlib.decompress(idat)
    rows: list[bytearray] = []
    prev = bytearray(stride)
    at = 0
    for _ in range(height):
        kind = raw[at]
        line = bytearray(raw[at + 1:at + 1 + stride])
        at += 1 + stride
        for i in range(stride):
            a = line[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if kind == 1:
                line[i] = (line[i] + a) & 0xFF
            elif kind == 2:
                line[i] = (line[i] + b) & 0xFF
            elif kind == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif kind == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
        rows.append(line)
        prev = line

    def samples(line: bytearray) -> list[int]:
        if depth == 8:
            return list(line)
        if depth == 16:
            return [line[i] for i in range(0, len(line), 2)]  # strip to 8 bits
        per = 8 // depth
        mask = (1 << depth) - 1
        out = []
        for byte in line:
            for k in range(per):
                out.append((byte >> (8 - depth * (k + 1))) & mask)
        return out

    out = bytearray()
    for line in rows:
        s = samples(line)
        for x in range(width):
            if ctype == 3:
                idx = s[x]
                r, g, b = plte[idx * 3:idx * 3 + 3]
                a = trns[idx] if trns is not None and idx < len(trns) else 255
            elif ctype == 0:
                v = s[x]
                if depth < 8:
                    v = v * 255 // ((1 << depth) - 1)
                r = g = b = v
                a = 0 if trns is not None and s[x] == (struct.unpack(">H", trns[:2])[0] >> (8 if depth == 16 else 0)) else 255
            elif ctype == 2:
                r, g, b = s[x * 3:x * 3 + 3]
                a = 255
                if trns is not None and len(trns) >= 6:
                    key = tuple(v >> (8 if depth == 16 else 0) for v in struct.unpack(">HHH", trns[:6]))
                    if (r, g, b) == key:
                        a = 0
            elif ctype == 4:
                r = g = b = s[x * 2]
                a = s[x * 2 + 1]
            else:
                r, g, b, a = s[x * 4:x * 4 + 4]
            out += bytes((r, g, b, a))
    return width, height, bytes(out)


def gen_images(src: Path, gen: Path) -> None:
    res = src / "frontends/framebuffer/res"
    for name, rel in FB_IMAGES.items():
        path = res / rel
        if not path.exists() and rel.startswith("throbber/"):
            path = src / "resources" / rel  # the framebuffer res/throbber files are symlinks to these
        w, h, px = png_rgba(path.read_bytes())

        def at(x: int, y: int) -> bytes:
            return px[(y * w + x) * 4:(y * w + x) * 4 + 4]

        # convert_image's detect_hotspot (its R/B byte offsets are swapped,
        # which does not matter for the pure-green marker pixels it looks for).
        cursor, greens, hot_x, hot_y = True, 0, 0, 0
        for i in range(w):
            r, g, b, a = at(i, 0)
            if a == 255:
                if g == 255:
                    greens, hot_x = greens + 1, i
                if r != 0 or b != 0:
                    cursor = False
                    break
            elif a != 0:
                cursor = False
                break
        if cursor and greens != 1:
            cursor = False
        if cursor:
            for i in range(h):
                r, g, b, a = at(0, i)
                if a == 255:
                    if g == 255:
                        greens, hot_y = greens + 1, i
                    if r != 0 or b != 0:
                        cursor = False
                        break
                elif a != 0:
                    cursor = False
                    break
            if cursor and greens != 2:
                cursor = False
        ow, oh = (w - 1, h - 1) if cursor else (w, h)
        ox = 1 if cursor else 0
        lines = [f"/* Generated from {rel} by ports/netsurf/gen_netsurf.py. */",
                 "#include <sys/types.h>", "#include <stdint.h>", "#include <stdbool.h>",
                 "#include <libnsfb.h>", '#include "netsurf/plot_style.h"',
                 '#include "framebuffer/gui.h"', '#include "framebuffer/fbtk.h"', "",
                 f"static uint8_t {name}_pixdata[] = {{"]
        for y in range(oh):
            row = b"".join(at(x + ox, y + ox) for x in range(ow))
            lines.append("\t" + " ".join(f"0x{v:02x}," for v in row))
        lines += ["};", "", f"struct fbtk_bitmap {name} = {{",
                  f"\t.width\t\t= {ow},", f"\t.height\t\t= {oh},",
                  f"\t.hot_x\t\t= {hot_x - 1 if cursor else 0},", f"\t.hot_y\t\t= {hot_y - 1 if cursor else 0},",
                  f"\t.pixdata\t= {name}_pixdata,", "};", ""]
        (gen / f"image-{name}.c").write_text("\n".join(lines))
    log(f"images: {len(FB_IMAGES)} toolkit bitmaps")


# ── testament.h ─────────────────────────────────────────────────────────────

def gen_testament(src: Path, gen: Path) -> None:
    rev = subprocess.run(["git", "rev-parse", "HEAD"], cwd=src, capture_output=True, text=True).stdout.strip()
    epoch = int(os.environ.get("SOURCE_DATE_EPOCH", "0"))
    date = time.strftime("%d.%m.%Y", time.gmtime(epoch))
    (gen / "testament.h").write_text(f"""/* Generated by ports/netsurf/gen_netsurf.py (tools/git-testament.pl's format). */
#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "{rev}"
#define USERNAME "papp"
#define GECOS "PAPP build"
#define WT_ROOT "/papp-src"
#define WT_HOSTNAME "papp-conversions"
#define WT_COMPILEDATE "{date}"
#define CI_BUILD "PAPP"
#define WT_BRANCHPATH "master"
#define WT_BRANCHISMASTER 1
#define WT_REVID "{rev}"
#define WT_MODIFIED 0
#define WT_MODIFICATIONS {{ \\
}}
#endif
""")


# ── Compiled-in resources ───────────────────────────────────────────────────
# resource: paths NetSurf asks the frontend for (content/fetchers/resource.c)
# and where their bytes come from. welcome.html is the port's own page.

RESOURCES = {
    "default.css": "resources/default.css",
    "adblock.css": "resources/adblock.css",
    "internal.css": "resources/internal.css",
    "quirks.css": "resources/quirks.css",
    "credits.html": "resources/en/credits.html",
    "licence.html": "resources/en/licence.html",
    "welcome.html": "local:ports/netsurf/res/welcome.html",
}


def c_bytes(name: str, data: bytes) -> list[str]:
    lines = [f"static const uint8_t {name}[{len(data) + 1}] = {{"]
    for i in range(0, len(data), 24):
        lines.append("\t" + ",".join(str(v) for v in data[i:i + 24]) + ",")
    lines.append("\t0\n};")  # NUL-terminated: some consumers treat it as a string
    return lines


def fat_messages(src: Path, lang: str = "en", platform: str = "fb") -> bytes:
    """tools/split-messages.pl -l en -p fb, as plain "key:value" lines."""
    out: dict[str, str] = {}
    pattern = re.compile(r"^([a-z]{2}(?:_[A-Z]{2})?).([^.]+).([^:]+):(.*)")
    for line in (src / "resources/FatMessages").read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or not line.strip():
            continue
        m = pattern.match(line)
        if not m:
            continue
        lng, plat, key, value = m.groups()
        if lng == lang and plat in ("all", platform):
            out[key] = value
    return "".join(f"{k}:{v}\n" for k, v in out.items()).encode("utf-8")


# What this port adds to NetSurf and the licence text each comes with, for
# the end of about:licence (the licences ask for their text to go along).
PORT_LICENCES = (
    ("DejaVu fonts 2.35", "https://dejavu-fonts.github.io/",
     "The fonts, cut down to fewer characters, keep their names; the licence allows that.",
     FONT_DIR + "/LICENSE_DEJAVU"),
    ("FreeType", "https://freetype.org/",
     "Portions of this software are copyright &copy; The FreeType Project (www.freetype.org). "
     "All rights reserved. FreeType is used under the FreeType License below (it may also be used under "
     "the GNU GPL version 2).",
     "libs/freetype/docs/FTL.TXT"),
    ("libwebp", "https://chromium.googlesource.com/webm/libwebp", "", "libs/libwebp/COPYING"),
    ("libsvgtiny", "https://www.netsurf-browser.org/projects/libsvgtiny/", "", "libs/libsvgtiny/COPYING"),
    ("Expat", "https://libexpat.github.io/", "", "libs/expat/expat/COPYING"),
)


def html_text(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def port_licences(src: Path) -> str:
    parts = ['<h2 class="ns-border">Added by the PAPP port</h2>\n',
             "<p>This build of NetSurf also contains the following, under these licences.</p>\n"]
    for name, url, note, rel in PORT_LICENCES:
        text = (src / rel).read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n").strip("\n")
        parts.append(f'<h3><a href="{url}">{name}</a></h3>\n')
        if note:
            parts.append(f"<p>{note}</p>\n")
        parts.append(f"<pre>{html_text(text)}</pre>\n")
    return "".join(parts)


def gen_resources(src: Path, gen: Path) -> None:
    lines = ["/* Generated by ports/netsurf/gen_netsurf.py: NetSurf's resources, compiled in. */",
             "#include <stddef.h>", "#include <stdint.h>", '#include "papp_resources.h"', ""]
    table = []
    for i, (name, rel) in enumerate(RESOURCES.items()):
        path = REPO / rel[len("local:"):] if rel.startswith("local:") else src / rel
        data = path.read_bytes()
        if name == "licence.html":
            marker = b'<div class="footer'
            if marker not in data:
                raise SystemExit("gen_netsurf: licence.html has no footer to put the port's licences before")
            data = data.replace(marker, port_licences(src).encode("utf-8") + b"\n" + marker, 1)
        lines += c_bytes(f"res_{i}", data) + [""]
        table.append(f'\t{{"{name}", res_{i}, {len(data)}}},')
    messages = fat_messages(src)
    lines += c_bytes("messages", messages) + [""]
    lines += ["const struct papp_resource papp_resources[] = {", *table, "\t{NULL, NULL, 0}", "};", "",
              "const uint8_t *const papp_messages = messages;",
              f"const size_t papp_messages_len = {len(messages)};", ""]
    (gen / "papp_resources.c").write_text("\n".join(lines))
    log(f"resources: {len(RESOURCES)} files, Messages {len(messages)} bytes")


def lint(units_path: Path) -> None:
    """Show the compiler's warnings for the port's own code and the patched
    NetSurf files (the build only reports errors). Never fails the build."""
    import json
    units = json.loads(units_path.read_text())
    patched = ("frontends/framebuffer/gui.c", "frontends/framebuffer/fetch.c", "content/fetch.c",
               "frontends/framebuffer/fbtk/text.c", "frontends/framebuffer/fbtk/event.c",
               "content/fetchers/about/query_privacy.c", "content/handlers/image/png.c",
               "content/handlers/image/jpeg.c", "frontends/framebuffer/framebuffer.c",
               "frontends/framebuffer/fbtk/fbtk.c", "frontends/framebuffer/fbtk/osk.c",
               "content/fetchers/about/about.c", "desktop/hotlist.c", "content/handlers/image/svg.c",
               "content/handlers/image/webp.c")
    serious = re.compile(r"implicit|incompatible|int-conversion|return-mismatch|uninitialized|overflow|"
                         r"array-bounds|format|sign-compare|unused-variable")
    checked = shown = 0
    for unit in units:
        src = unit["src"].replace("\\", "/")
        own = "/ports/netsurf/" in src
        if not own and not src.endswith(patched):
            continue
        checked += 1
        result = subprocess.run([unit["compiler"], *unit["flags"], "-Wall", "-Wextra", "-Wno-unused-parameter",
                                 "-Wno-sign-compare", "-fsyntax-only", unit["src"]],
                                capture_output=True, text=True)
        lines = [l for l in result.stderr.splitlines() if "warning:" in l or "error:" in l]
        if not own:
            lines = [l for l in lines if serious.search(l) and "/ports/netsurf/" not in l]
        for line in lines[:20]:
            log("lint: " + re.sub(r"^\S*/(ports/netsurf/|src-[^/]+/)", "", line)[:240])
        shown += len(lines)
    log(f"lint: {checked} files checked, {shown} warnings")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--src", type=Path, required=True)
    parser.add_argument("--gen", type=Path, required=True)
    parser.add_argument("--units", type=Path)
    args = parser.parse_args()
    src, gen = args.src.resolve(), args.gen.resolve()
    gen.mkdir(parents=True, exist_ok=True)
    log(f"host cc: {shutil.which('cc') or shutil.which('gcc') or 'none'}, perl: {shutil.which('perl') or 'none'}, "
        f"gperf: {shutil.which('gperf') or 'none'}")
    gen_libcss(src, gen)
    gen_hubbub(src, gen)
    gen_parserutils(src)
    gen_svgtiny(src, gen)
    gen_dom_headers(src, gen)
    gen_image_libs(src, gen)
    gen_expat(src, gen)
    gen_fonts(src, gen)
    gen_images(src, gen)
    gen_testament(src, gen)
    gen_resources(src, gen)
    shutil.rmtree(gen / "tools", ignore_errors=True)
    if args.units is not None:
        lint(args.units)
    return 0


if __name__ == "__main__":
    sys.exit(main())
