#!/usr/bin/env python3
"""Prebuild step for the NetSurf PAPP (apps/psram_netsurf/papp.json).

NetSurf and its libraries generate some sources with host tools before they
compile. This does the same with the build machine's tools, inside the source
checkout that tools/build_papp.py prepared:

- libcss: the property parsers (css_property_parser_gen, from properties.gen)
- libhubbub: the entity table (make-entities.pl) and the element-type hash
  (gperf; written to .papp-gen/hubbub so the "*.c" group does not pick it up)
- libparserutils: the charset alias table (make-aliases.pl)
- NetSurf framebuffer frontend: the internal bitmap font (convert_font), the
  toolkit images (the PNG icons, pointers and throbber decoded here instead of
  with libpng, in convert_image's output format) and testament.h
- the resources NetSurf serves from resource: URLs and its Messages file,
  compiled in (papp_resources.c), so the app runs with nothing on the card
- libdom's hubbub binding headers as <dom/bindings/hubbub/...>

Everything is reproducible: no timestamps, host names or paths end up in the
output except what SOURCE_DATE_EPOCH gives.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import struct
import subprocess
import sys
import time
import zlib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
PORT = REPO / "ports" / "netsurf"


def log(msg: str) -> None:
    print(f"  [gen] {msg}", flush=True)


def run(cmd: list[str], **kwargs) -> None:
    subprocess.run([str(c) for c in cmd], check=True, **kwargs)


def need(tool: str, package: str) -> str:
    """Path of a host tool; installs its Debian package if it is missing (CI container)."""
    found = shutil.which(tool)
    if found:
        return found
    if shutil.which("apt-get") and hasattr(os, "geteuid") and os.geteuid() == 0:
        log(f"{tool} missing, installing {package}")
        subprocess.run(["apt-get", "update", "-qq"], check=False, stdout=subprocess.DEVNULL)
        subprocess.run(["apt-get", "install", "-y", "-qq", package], check=False, stdout=subprocess.DEVNULL)
        found = shutil.which(tool)
    if not found:
        raise SystemExit(f"gen_netsurf: '{tool}' is needed (package {package})")
    return found


def host_cc() -> str:
    return shutil.which("cc") or shutil.which("gcc") or need("gcc", "gcc")


# ── libcss ──────────────────────────────────────────────────────────────────

def gen_libcss(src: Path, gen: Path) -> None:
    props = src / "libs/libcss/src/parse/properties"
    tool = gen / "tools" / "css_property_parser_gen"
    tool.parent.mkdir(parents=True, exist_ok=True)
    run([host_cc(), "-O1", "-o", tool, props / "css_property_parser_gen.c"])
    count = 0
    for line in (props / "properties.gen").read_text().splitlines():
        m = re.match(r"^([^#][^:]+):", line)
        if not m:
            continue
        run([tool, "-o", props / f"autogenerated_{m.group(1)}.c", line.strip()], stdout=subprocess.DEVNULL)
        count += 1
    log(f"libcss: {count} property parsers")


# ── libhubbub / libparserutils ──────────────────────────────────────────────

def gen_hubbub(src: Path, gen: Path) -> None:
    lib = src / "libs/libhubbub"
    run([need("perl", "perl"), "build/make-entities.pl"], cwd=lib, stdout=subprocess.DEVNULL)
    out = gen / "hubbub" / "treebuilder" / "autogenerated-element-type.c"
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_suffix(".tmp")
    run([need("gperf", "gperf"), f"--output-file={tmp}", lib / "src/treebuilder/element-type.gperf"])
    text = tmp.read_text()
    tmp.unlink()
    # As the upstream Makefile's sed: the table is file-local.
    text = re.sub(r"^(const struct element_type_map)", r"static \1", text, flags=re.M)
    # gperf records the input path in #line directives; keep it out of the build.
    text = text.replace(str(lib) + "/", "")
    out.write_text(text)
    log("libhubbub: entities.inc, autogenerated-element-type.c")


def gen_parserutils(src: Path) -> None:
    run([need("perl", "perl"), "build/make-aliases.pl"], cwd=src / "libs/libparserutils", stdout=subprocess.DEVNULL)
    log("libparserutils: aliases.inc")


def gen_dom_headers(src: Path, gen: Path) -> None:
    out = gen / "include" / "dom" / "bindings" / "hubbub"
    out.mkdir(parents=True, exist_ok=True)
    for name in ("parser.h", "errors.h"):
        shutil.copyfile(src / "libs/libdom/bindings/hubbub" / name, out / name)


# ── Framebuffer font ────────────────────────────────────────────────────────

def gen_font(src: Path, gen: Path) -> None:
    tool = gen / "tools" / "convert_font"
    run([host_cc(), "-O1", "-o", tool, src / "tools/convert_font.c"])
    run([tool, "-q", "-H", gen / "font-ns-sans.h",
         src / "frontends/framebuffer/res/fonts/glyph_data", gen / "font-ns-sans.c"], stdout=subprocess.DEVNULL)
    log("font: font-ns-sans.c")


# ── Framebuffer toolkit images ──────────────────────────────────────────────
# frontends/framebuffer/Makefile's FB_IMAGE_* list, converted like
# tools/convert_image.c does with libpng.

FB_IMAGES = {
    "left_arrow": "icons/back.png",
    "right_arrow": "icons/forward.png",
    "reload": "icons/reload.png",
    "stop_image": "icons/stop.png",
    "history_image": "icons/history.png",
    "left_arrow_g": "icons/back_g.png",
    "right_arrow_g": "icons/forward_g.png",
    "reload_g": "icons/reload_g.png",
    "stop_image_g": "icons/stop_g.png",
    "history_image_g": "icons/history_g.png",
    "scrolll": "icons/scrolll.png",
    "scrollr": "icons/scrollr.png",
    "scrollu": "icons/scrollu.png",
    "scrolld": "icons/scrolld.png",
    "osk_image": "icons/osk.png",
    "pointer_image": "pointers/default.png",
    "hand_image": "pointers/point.png",
    "caret_image": "pointers/caret.png",
    "menu_image": "pointers/menu.png",
    "progress_image": "pointers/progress.png",
    "move_image": "pointers/move.png",
    **{f"throbber{i}": f"throbber/throbber{i}.png" for i in range(9)},
}


def png_rgba(data: bytes) -> tuple[int, int, bytes]:
    """Decode a PNG to 8-bit RGBA (what convert_image asks libpng for)."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    pos, idat, plte, trns = 8, b"", b"", None
    width = height = depth = ctype = interlace = 0
    while pos < len(data):
        length, kind = struct.unpack(">I4s", data[pos:pos + 8])
        body = data[pos + 8:pos + 8 + length]
        pos += 12 + length
        if kind == b"IHDR":
            width, height, depth, ctype, _, _, interlace = struct.unpack(">IIBBBBB", body)
        elif kind == b"PLTE":
            plte = body
        elif kind == b"tRNS":
            trns = body
        elif kind == b"IDAT":
            idat += body
        elif kind == b"IEND":
            break
    if interlace:
        raise ValueError("interlaced PNGs are not supported")
    channels = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ctype]
    bits = channels * depth
    stride = (width * bits + 7) // 8
    bpp = max(1, bits // 8)
    raw = zlib.decompress(idat)
    rows: list[bytearray] = []
    prev = bytearray(stride)
    at = 0
    for _ in range(height):
        kind = raw[at]
        line = bytearray(raw[at + 1:at + 1 + stride])
        at += 1 + stride
        for i in range(stride):
            a = line[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if kind == 1:
                line[i] = (line[i] + a) & 0xFF
            elif kind == 2:
                line[i] = (line[i] + b) & 0xFF
            elif kind == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif kind == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
        rows.append(line)
        prev = line

    def samples(line: bytearray) -> list[int]:
        if depth == 8:
            return list(line)
        if depth == 16:
            return [line[i] for i in range(0, len(line), 2)]  # strip to 8 bits
        per = 8 // depth
        mask = (1 << depth) - 1
        out = []
        for byte in line:
            for k in range(per):
                out.append((byte >> (8 - depth * (k + 1))) & mask)
        return out

    out = bytearray()
    for line in rows:
        s = samples(line)
        for x in range(width):
            if ctype == 3:
                idx = s[x]
                r, g, b = plte[idx * 3:idx * 3 + 3]
                a = trns[idx] if trns is not None and idx < len(trns) else 255
            elif ctype == 0:
                v = s[x]
                if depth < 8:
                    v = v * 255 // ((1 << depth) - 1)
                r = g = b = v
                a = 0 if trns is not None and s[x] == (struct.unpack(">H", trns[:2])[0] >> (8 if depth == 16 else 0)) else 255
            elif ctype == 2:
                r, g, b = s[x * 3:x * 3 + 3]
                a = 255
                if trns is not None and len(trns) >= 6:
                    key = tuple(v >> (8 if depth == 16 else 0) for v in struct.unpack(">HHH", trns[:6]))
                    if (r, g, b) == key:
                        a = 0
            elif ctype == 4:
                r = g = b = s[x * 2]
                a = s[x * 2 + 1]
            else:
                r, g, b, a = s[x * 4:x * 4 + 4]
            out += bytes((r, g, b, a))
    return width, height, bytes(out)


def gen_images(src: Path, gen: Path) -> None:
    res = src / "frontends/framebuffer/res"
    for name, rel in FB_IMAGES.items():
        path = res / rel
        if not path.exists() and rel.startswith("throbber/"):
            path = src / "resources" / rel  # the framebuffer res/throbber files are symlinks to these
        w, h, px = png_rgba(path.read_bytes())

        def at(x: int, y: int) -> bytes:
            return px[(y * w + x) * 4:(y * w + x) * 4 + 4]

        # convert_image's detect_hotspot (its R/B byte offsets are swapped,
        # which does not matter for the pure-green marker pixels it looks for).
        cursor, greens, hot_x, hot_y = True, 0, 0, 0
        for i in range(w):
            r, g, b, a = at(i, 0)
            if a == 255:
                if g == 255:
                    greens, hot_x = greens + 1, i
                if r != 0 or b != 0:
                    cursor = False
                    break
            elif a != 0:
                cursor = False
                break
        if cursor and greens != 1:
            cursor = False
        if cursor:
            for i in range(h):
                r, g, b, a = at(0, i)
                if a == 255:
                    if g == 255:
                        greens, hot_y = greens + 1, i
                    if r != 0 or b != 0:
                        cursor = False
                        break
                elif a != 0:
                    cursor = False
                    break
            if cursor and greens != 2:
                cursor = False
        ow, oh = (w - 1, h - 1) if cursor else (w, h)
        ox = 1 if cursor else 0
        lines = [f"/* Generated from {rel} by ports/netsurf/gen_netsurf.py. */",
                 "#include <sys/types.h>", "#include <stdint.h>", "#include <stdbool.h>",
                 "#include <libnsfb.h>", '#include "netsurf/plot_style.h"',
                 '#include "framebuffer/gui.h"', '#include "framebuffer/fbtk.h"', "",
                 f"static uint8_t {name}_pixdata[] = {{"]
        for y in range(oh):
            row = b"".join(at(x + ox, y + ox) for x in range(ow))
            lines.append("\t" + " ".join(f"0x{v:02x}," for v in row))
        lines += ["};", "", f"struct fbtk_bitmap {name} = {{",
                  f"\t.width\t\t= {ow},", f"\t.height\t\t= {oh},",
                  f"\t.hot_x\t\t= {hot_x - 1 if cursor else 0},", f"\t.hot_y\t\t= {hot_y - 1 if cursor else 0},",
                  f"\t.pixdata\t= {name}_pixdata,", "};", ""]
        (gen / f"image-{name}.c").write_text("\n".join(lines))
    log(f"images: {len(FB_IMAGES)} toolkit bitmaps")


# ── testament.h ─────────────────────────────────────────────────────────────

def gen_testament(src: Path, gen: Path) -> None:
    rev = subprocess.run(["git", "rev-parse", "HEAD"], cwd=src, capture_output=True, text=True).stdout.strip()
    epoch = int(os.environ.get("SOURCE_DATE_EPOCH", "0"))
    date = time.strftime("%d.%m.%Y", time.gmtime(epoch))
    (gen / "testament.h").write_text(f"""/* Generated by ports/netsurf/gen_netsurf.py (tools/git-testament.pl's format). */
#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "{rev}"
#define USERNAME "papp"
#define GECOS "PAPP build"
#define WT_ROOT "/papp-src"
#define WT_HOSTNAME "papp-conversions"
#define WT_COMPILEDATE "{date}"
#define CI_BUILD "PAPP"
#define WT_BRANCHPATH "master"
#define WT_BRANCHISMASTER 1
#define WT_REVID "{rev}"
#define WT_MODIFIED 0
#define WT_MODIFICATIONS {{ \\
}}
#endif
""")


# ── Compiled-in resources ───────────────────────────────────────────────────
# resource: paths NetSurf asks the frontend for (content/fetchers/resource.c)
# and where their bytes come from. welcome.html is the port's own page.

RESOURCES = {
    "default.css": "resources/default.css",
    "adblock.css": "resources/adblock.css",
    "internal.css": "resources/internal.css",
    "quirks.css": "resources/quirks.css",
    "credits.html": "resources/en/credits.html",
    "licence.html": "resources/en/licence.html",
    "welcome.html": "local:ports/netsurf/res/welcome.html",
}


def c_bytes(name: str, data: bytes) -> list[str]:
    lines = [f"static const uint8_t {name}[{len(data) + 1}] = {{"]
    for i in range(0, len(data), 24):
        lines.append("\t" + ",".join(str(v) for v in data[i:i + 24]) + ",")
    lines.append("\t0\n};")  # NUL-terminated: some consumers treat it as a string
    return lines


def fat_messages(src: Path, lang: str = "en", platform: str = "fb") -> bytes:
    """tools/split-messages.pl -l en -p fb, as plain "key:value" lines."""
    out: dict[str, str] = {}
    pattern = re.compile(r"^([a-z]{2}(?:_[A-Z]{2})?).([^.]+).([^:]+):(.*)")
    for line in (src / "resources/FatMessages").read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or not line.strip():
            continue
        m = pattern.match(line)
        if not m:
            continue
        lng, plat, key, value = m.groups()
        if lng == lang and plat in ("all", platform):
            out[key] = value
    return "".join(f"{k}:{v}\n" for k, v in out.items()).encode("utf-8")


def gen_resources(src: Path, gen: Path) -> None:
    lines = ["/* Generated by ports/netsurf/gen_netsurf.py: NetSurf's resources, compiled in. */",
             "#include <stddef.h>", "#include <stdint.h>", '#include "papp_resources.h"', ""]
    table = []
    for i, (name, rel) in enumerate(RESOURCES.items()):
        path = REPO / rel[len("local:"):] if rel.startswith("local:") else src / rel
        data = path.read_bytes()
        lines += c_bytes(f"res_{i}", data) + [""]
        table.append(f'\t{{"{name}", res_{i}, {len(data)}}},')
    messages = fat_messages(src)
    lines += c_bytes("messages", messages) + [""]
    lines += ["const struct papp_resource papp_resources[] = {", *table, "\t{NULL, NULL, 0}", "};", "",
              "const uint8_t *const papp_messages = messages;",
              f"const size_t papp_messages_len = {len(messages)};", ""]
    (gen / "papp_resources.c").write_text("\n".join(lines))
    log(f"resources: {len(RESOURCES)} files, Messages {len(messages)} bytes")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--src", type=Path, required=True)
    parser.add_argument("--gen", type=Path, required=True)
    args = parser.parse_args()
    src, gen = args.src.resolve(), args.gen.resolve()
    gen.mkdir(parents=True, exist_ok=True)
    log(f"host cc: {shutil.which('cc') or shutil.which('gcc') or 'none'}, perl: {shutil.which('perl') or 'none'}, "
        f"gperf: {shutil.which('gperf') or 'none'}")
    gen_libcss(src, gen)
    gen_hubbub(src, gen)
    gen_parserutils(src)
    gen_dom_headers(src, gen)
    gen_font(src, gen)
    gen_images(src, gen)
    gen_testament(src, gen)
    gen_resources(src, gen)
    shutil.rmtree(gen / "tools", ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
